name = "tutorial-hello-world"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "tutorial-hello-world_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "tutorial-hello-world.wasm"
command = "npm run build:release"
